stages:
- install
install:
  stage: install
  image: maven:3.5-jdk-8
  before_script:
  - java -version
  - chmod +x mvnw
  script:
  - ./mvnw -e clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dspring-boot.run.profiles=dev
  - ./mvnw -e clean install -DskipTests=true -Dmaven.javadoc.skip=true -Dspring-boot.run.profiles=prod